# Generated by Django 5.2.1 on 2025-05-25 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_product_descriotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 10, 58, 11, 352411)),
        ),
    ]
