# Generated by Django 5.0.3 on 2025-06-07 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_category_alter_product_created_at_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
